name: CI-BOB-Unittest

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:    
      # 우리 코드 체크아웃(가상 머신에 우리 코드 다운로드 (git clone))
      # 여기서 use는 import와 비슷한 개념이다.
      # github에 actions라는 endpoint 가보면 이것저것 많이 있음
      - uses: actions/checkout@v2

      # 우리 코드를 돌릴 것임
      - name: Run pwd
        run: pwd
      - name: Check directory
        run: ls -al

      # 우분투 위에 필요한 언어/프레임워크/환경 설치 
      - name: Setup python
        uses: actions/setup-python@v2
        with: 
          python-version: 3.7

      # 필요 소프트웨어 패키지 설치 
      - name: Install pip, pytest
        run: | 
          python -m pip install --upgrade pip
          pip install pytest

      # 파이썬 유닛 테스트를 돌릴 거임
      - name: Run my unittest
        run: 
          pytest  