name: CI-BOB-Unittest

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:    
      # 우리 코드 체크아웃(가상 머신에 우리 코드 다운로드 (git clone))
      # 여기서 use는 import와 비슷한 개념이다.
      # github에 actions라는 endpoint 가보면 이것저것 많이 있음
      - uses: actions/checkout@v2

      # 우리 코드를 돌릴 것임
      - name: Run pwd
        run: pwd
      - name: Check directory
        run: ls -al

      # 우분투 위에 패키지 설치 
      # 파이썬 유닛 테스트를 돌릴 거임